[package]
name = "nye-projects"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.104"
dedent = "0.1.1"
nye-packages = { path = "../nye-packages" }
nye-schemas = { path = "../nye-schemas" }
nye-validation = { path = "../nye-validation" }
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["fs"] }
toml = "1.1.6"
