[package]
name = 'example'
version = '0.1.0'

[targets]
[targets.linux-amd64]
source = 'src/linux-amd64'

[[exposes.bin]]
path = "busybox"
links = ["cd", "ls", "cp", "mv", "rm", "sh", "busybox"]
targets = ["linux-amd64"]

[consumes]
env = []
