[package]
name = "nye"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.104", features = ["backtrace"] }
async_zip = { version = "0.0.19", features = ["tokio", "tokio-fs"] }
clap = { version = "4.6.6", features = ["derive", "env", "wrap_help"] }
colored = "3.1.1"
dedent = "0.1.1"
globwalk = "0.9.1"
indicatif = { version = "0.18.6", features = ["tokio"] }
path-clean = "1.0.1"
pathdiff = "0.2.3"
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["fs", "io-std", "io-util", "macros", "rt", "rt-multi-thread"] }
tokio-util = { version = "0.7.19", features = ["futures-io", "io", "io-util"] }
toml = { version = "1.1.4", features = ["preserve_order", "serde"] }
users = "0.11.0"
