[workspace]
members = [
    "crates/nye",
    "crates/nye-environment",
    "crates/nye-keyring-daemon",
    "crates/nye-keyring-daemon-protocol", "crates/nye-packages", "crates/nye-projects",
    "crates/nye-registry",
    "crates/nye-registry-client",
    "crates/nye-registry-client-http",
    "crates/nye-registry-client-local",
    "crates/nye-schemas", "crates/nye-utils", "crates/nye-validation",
]
resolver = "3"

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
debug = false
overflow-checks = false
incremental = false
