version = 1

[schema]

[[schema.tables]]
id = 0
name = "users"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "email"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 3 }
name = "password"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 4 }
name = "created_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 5 }
name = "updated_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_users_by_id"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 0, index = 1 }
name = "index_users_by_name"
on = 0
columns = [{ column = { table = 0, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables.indices]]
id = { table = 0, index = 2 }
name = "index_users_by_email"
on = 0
columns = [{ column = { table = 0, index = 2 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 1
name = "packages"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "user_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 3 }
name = "created_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 4 }
name = "updated_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_packages_by_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 1, index = 1 }
name = "index_packages_by_name"
on = 1
columns = [{ column = { table = 1, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables.indices]]
id = { table = 1, index = 2 }
name = "index_packages_by_user_id"
on = 1
columns = [{ column = { table = 1, index = 2 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 2
name = "package_versions"
primary_key = { columns = [{ table = 2, index = 0 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "number"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 2 }
name = "package_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 3 }
name = "created_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 4 }
name = "updated_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_package_versions_by_id"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 2, index = 1 }
name = "index_package_versions_by_package_id_and_number"
on = 2
columns = [{ column = { table = 2, index = 2 }, op = "Eq", scope = "Partition" }, { column = { table = 2, index = 1 }, op = "Eq", scope = "Local" }]
unique = true

[[schema.tables.indices]]
id = { table = 2, index = 2 }
name = "index_package_versions_by_package_id"
on = 2
columns = [{ column = { table = 2, index = 2 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 3
name = "package_version_bundles"
primary_key = { columns = [{ table = 3, index = 0 }], index = { table = 3, index = 0 } }

[[schema.tables.columns]]
id = { table = 3, index = 0 }
name = "id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 1 }
name = "target_os"
ty = "String"
storage_ty = { Enum = { name = "os", variants = [{ name = "linux" }, { name = "windows" }, { name = "mac_os" }, { name = "android" }, { name = "ios" }, { name = "open_bsd" }, { name = "free_bsd" }, { name = "net_bsd" }, { name = "wasi" }, { name = "hermit" }, { name = "aix" }, { name = "apple" }, { name = "dragonfly" }, { name = "emscripten" }, { name = "espidf" }, { name = "fortanix" }, { name = "uefi" }, { name = "fuchsia" }, { name = "haiku" }, { name = "watch_os" }, { name = "vision_os" }, { name = "tv_os" }, { name = "horizon" }, { name = "hurd" }, { name = "illumos" }, { name = "l4re" }, { name = "nto" }, { name = "redox" }, { name = "solaris" }, { name = "solid_asp3" }, { name = "vexos" }, { name = "vita" }, { name = "vxworks" }, { name = "xous" }] } }

[[schema.tables.columns]]
id = { table = 3, index = 2 }
name = "target_arch"
ty = "String"
storage_ty = { Enum = { name = "arch", variants = [{ name = "x86" }, { name = "x86_64" }, { name = "arm" }, { name = "aarch64" }, { name = "m68k" }, { name = "mips" }, { name = "mips32r6" }, { name = "mips64" }, { name = "mips64r6" }, { name = "csky" }, { name = "powerpc" }, { name = "powerpc64" }, { name = "riscv32" }, { name = "riscv64" }, { name = "s390x" }, { name = "sparc" }, { name = "sparc64" }, { name = "hexagon" }, { name = "loongarch32" }, { name = "loongarch64" }] } }

[[schema.tables.columns]]
id = { table = 3, index = 3 }
name = "file"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 4 }
name = "version_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 5 }
name = "created_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 6 }
name = "updated_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 3, index = 0 }
name = "index_package_version_bundles_by_id"
on = 3
columns = [{ column = { table = 3, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 3, index = 1 }
name = "index_package_version_bundles_by_version_id"
on = 3
columns = [{ column = { table = 3, index = 4 }, op = "Eq", scope = "Partition" }]
