version = 1

[schema]

[[schema.tables]]
id = 0
name = "users"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "email"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 3 }
name = "password"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 4 }
name = "created_at"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 0, index = 5 }
name = "updated_at"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_users_by_id"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 0, index = 1 }
name = "index_users_by_name"
on = 0
columns = [{ column = { table = 0, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables.indices]]
id = { table = 0, index = 2 }
name = "index_users_by_email"
on = 0
columns = [{ column = { table = 0, index = 2 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 1
name = "tokens"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "kind"
ty = "String"
storage_ty = { Enum = { name = "token_kind", variants = [{ name = "access" }, { name = "refresh" }] } }

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "user_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 3 }
name = "created_at"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 1, index = 4 }
name = "updated_at"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 1, index = 5 }
name = "expires_at"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_tokens_by_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 1, index = 1 }
name = "index_tokens_by_user_id"
on = 1
columns = [{ column = { table = 1, index = 2 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 2
name = "packages"
primary_key = { columns = [{ table = 2, index = 0 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 2 }
name = "user_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 3 }
name = "created_at"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 2, index = 4 }
name = "updated_at"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_packages_by_id"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 2, index = 1 }
name = "index_packages_by_name"
on = 2
columns = [{ column = { table = 2, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables.indices]]
id = { table = 2, index = 2 }
name = "index_packages_by_user_id"
on = 2
columns = [{ column = { table = 2, index = 2 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 3
name = "package_versions"
primary_key = { columns = [{ table = 3, index = 0 }], index = { table = 3, index = 0 } }

[[schema.tables.columns]]
id = { table = 3, index = 0 }
name = "id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 1 }
name = "number"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 2 }
name = "package_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 3 }
name = "created_at"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 3, index = 4 }
name = "updated_at"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.indices]]
id = { table = 3, index = 0 }
name = "index_package_versions_by_id"
on = 3
columns = [{ column = { table = 3, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 3, index = 1 }
name = "index_package_versions_by_package_id_and_number"
on = 3
columns = [{ column = { table = 3, index = 2 }, op = "Eq", scope = "Partition" }, { column = { table = 3, index = 1 }, op = "Eq", scope = "Local" }]
unique = true

[[schema.tables.indices]]
id = { table = 3, index = 2 }
name = "index_package_versions_by_package_id"
on = 3
columns = [{ column = { table = 3, index = 2 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 4
name = "package_version_bundles"
primary_key = { columns = [{ table = 4, index = 0 }], index = { table = 4, index = 0 } }

[[schema.tables.columns]]
id = { table = 4, index = 0 }
name = "id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 1 }
name = "target"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 2 }
name = "file"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 3 }
name = "version_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 4 }
name = "created_at"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 4, index = 5 }
name = "updated_at"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.indices]]
id = { table = 4, index = 0 }
name = "index_package_version_bundles_by_id"
on = 4
columns = [{ column = { table = 4, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 4, index = 1 }
name = "index_package_version_bundles_by_version_id_and_target"
on = 4
columns = [{ column = { table = 4, index = 3 }, op = "Eq", scope = "Partition" }, { column = { table = 4, index = 1 }, op = "Eq", scope = "Local" }]
unique = true

[[schema.tables.indices]]
id = { table = 4, index = 2 }
name = "index_package_version_bundles_by_version_id"
on = 4
columns = [{ column = { table = 4, index = 3 }, op = "Eq", scope = "Partition" }]
